### ISSUE TITLE
How to convert this rango project to normal website

### ISSUE THREAD

**Issue by Angela111** [leifos/tango_with_django_17#3]
Currently, we run the rango project as "http://127.0.0.1:8000/...". Then how can we convert it to normal URL, such as "http://www.tangowithdjango.com/..."?

**Comment by Copser** [comment]
To make it work you need to marge it to some server, or hosts like https://www.pythonanywhere.com, or https://www.heroku.com/, further more you need to make your local project live. Check this tutorial too http://tutorial.djangogirls.org/en/django_urls/README.html, it is a little lighter the this one, but also effective. 
But isn't there a section in tutorial where you take your local rango project and make it a live one?

**Comment by Copser** [comment]
Yes, this is it http://www.tangowithdjango.com/book17/chapters/deploy.html, just push further into the tutorial and you will see how can you do it, I am you will make it alive.

**Comment by Copser** [comment]
Just one more thing, if you are interested in learning django stick whit djangogirls community, they are extremely helpful whit helping newcomers, and ofc the official site www.djangoproject.com.

**Comment by Angela111** [comment]
OK. Thanks a lot!

**Comment by Copser** [comment]
No problem, check this one too, it a killer and it is a new django verison 1.8 tutorial http://www.marinamele.com/taskbuster-django-tutorial.

**Comment by Angela111** [comment]
Thanks again. You're so nice!

**Comment by Copser** [comment]
Heh, well it is a open source so someone help'd me too, I am just returning it to someone else, that is how things flow whit django.
Close the issue when you can and in the future ask for help here on https://gitter.im/DjangoGirls/tutorial, Django IRC, or http://stackoverflow.com/.
Best and thank you.

**Comment by Angela111** [comment]
:-D

**Comment by leifos** [comment]
Great glad you found the answers - btw, the taskbuster tutorial looks good, thanks for the tip!
