### ISSUE TITLE
Tango With Django Ch13 TemplateSyntaxError

### ISSUE THREAD

**Issue by FroggyRiseman** [leifos/tango_with_django_17#4]
Hey, @leifos and others who may be willing to help! I'm pretty new to programming and I've come to my first problem on Tango With Django on Chapter 13.

I copied and pasted your "raw" code for bootstrap_base.html into my base.html file and when I do `python manage.py runserver` and go to the url I am getting multiple syntax errors.

I am getting: `Invalid block tag: 'get_category_list', expected 'endblock'` on line 79. I've tried cleaning up the code to make it easier to read and check for easily noticeable syntax errors, but there are none. I even tried using [pgrfx's](https://github.com/paulgrfx/tango_with_django/blob/master/templates/base.html) version of base.html for the course and I get the same syntax error.
I tried deleting line 79 and I am now getting another error at line 107: `Invalid block tag: 'static'`.
I'm certain the following line will pull up another error if I delete line 107.
I also opened up the actual base.html file itself in the browser to make sure it worked and everything looks good minus the sections where I can see the block tags(code).

I haven't downloaded bootstrap (doesn't look to be the issue) and have only gotten to the beginning section of Chapter 13.2 (only editing base.html - this might be the issue).

Might [this](https://stackoverflow.com/questions/24093018/invalid-block-tag-gettweet-expected-endblock-for-django-project) be a solution for the first TemplateSyntaxError? I have checked Ch14 and noticed that this is called from a function created at the beginning of that chapter but do not wish to fast-forward without getting a grasp on exactly what I'm missing here in Ch13.

Any help on where I am making my mistake?

**Comment by FroggyRiseman** [comment]
Common sense says I was skipping ahead and sure enough I was. I had copied your file, @leifos  when in fact I should I have copied the code off the actual [site](http://www.tangowithdjango.com/book17/chapters/bootstrap.html) itself.

Sorry if I wasted anybody's' time.

**Comment by leifos** [comment]
No worries. Glad you resolved the problem :-)
